### PR TITLE
feat: Update GraphQL endpoint, support AVC1 encoded URLs, add URL detection pattern, and update RequestDetails.json

### PR DESCRIPTION
**Pull request by 7rikazhexde**
# Changes

Six changes are proposed.

1. Change in GraphQL endpoint URL (#28)
2. Support for changed video URLs (AVC1 encoding)
3. Addition of URL detection pattern (x)
4. Update to RequestDetails.json (auto-update)
5. URL detection pattern (3. commit update)
6. Add headers to requests.get in tweet_url retrieval (#32, #34, #35, #36)

# Details

## 1. Change in GraphQL endpoint URL

This is the same as [#28](https://github.com/inteoryx/twitter-video-dl/pull/28). There was no problem with the first modification in my environment.

## 2. Support for changed video URLs (AVC1 encoding)

AVC1 encoding has been added to the video URL. I would like to propose a pattern that includes avc1 as a modification.   
This can be used for both avc1 and non-avc1 URLs, as there are URLs that do not include avc1 in the videos posted so far.

The URL details are as follows.
https://github.com/7rikazhexde/twitter-video-dl-for-sc/issues/4

## 3. Addition of URL detection pattern (x)

Since there are two URLs in the video, twitter and x, a pattern is added.

### get_tweet_status_id function

Change detection pattern for status_id

### get_associated_media_id function

Change detection pattern for id_str

### extract_mp4s function

Change video extraction pattern (amplitude_pattern,ext_tw_pattern)

## 5. URL detection pattern

Allow URL patterns to be detected for both X and twitter (3. commit update).

## 6.  Add headers to requests.get in tweet_url retrieval

The modifications are the same as the following modifications.
https://github.com/7rikazhexde/twitter-video-dl-for-sc/issues/7

### CODE REVIEW

**Comment by 7rikazhexde** [comment]
@inteoryx 
Pull requests have been updated.
Issue registrations are increasing. Please consider merge approval.

**Comment by L1ghtmann** [comment]
Bump

**Comment by yarodevuci** [comment]
Twitter URL not found error...

**Comment by 7rikazhexde** [comment]
The error "Failed to find main.js file" has been confirmed in issue (https://github.com/7rikazhexde/twitter-video-dl-for-sc/issues/16), and it has been able to be fixed.

> Cause
> Sending a GET request with a submission page URL specification now redirects to the authentication page.

I plan to commit the same fix, but please be aware that there might be further changes to the specifications on X. (When I tried to commit the fix, there were additional changes.)

**Comment by yarodevuci** [comment]
@7rikazhexde as a walk around, I ditched the guest token and using Bearer token manually pulled from browser after Login...

**Comment by yarodevuci** [comment]
@7rikazhexde does your latest fix allows to bypass personal Bearer token ?

**Comment by 7rikazhexde** [comment]
@yarodevuci
Yes, with the latest changes, the code now automatically retrieves both the bearer token and the guest token. This means you no longer need to manually retrieve the bearer token from the browser after login, effectively bypassing the need for a personal bearer token.

However, if you still wish to use a manually retrieved bearer token for some reason, you can override the automatically retrieved token by replacing the following line:
`bearer_token = bearer_token[0]`

**Comment by 7rikazhexde** [comment]
@inteoryx
Sorry, but for personal reasons, I closed this pull request. I plan to submit a new one at a later time.

**Pull request closed without merging**
